package com.hillspet.wearables.common.constants;

/**
 * @author vvodyaram This Class contains all the PROCEDURE and FUNCTION CALLS
 */
public interface SQLConstants {

	String RESULT_SET_1 = "#result-set-1";
	String RESULT_SET_2 = "#result-set-2";
	String RESULT_SET_3 = "#result-set-3";
	String RESULT_SET_4 = "#result-set-4";

	/* device info related procedures */
	String DEVICE_INFO_INSERT = "DEVICE_INFO_INSERT";
	String DEVICE_INFO_UPDATE = "DEVICE_INFO_UPDATE";
	String DEVICE_INFO_DELETE = "DEVICE_INFO_DELETE";
	String DEVICE_INFO_UPDATE_DEVICE_FIRMWARE = "DEVICE_INFO_UPDATE_DEVICE_FIRMWARE";
	String DEVICE_INFO_GET_BY_ID = "CALL DEVICE_INFO_GET_BY_ID (?)";
	String DEVICE_INFO_GET_LIST = "CALL DEVICE_INFO_GET_LIST (?,?,?,?,?,?,?,?,?,?)";
	String ASSET_GET_LIST = "CALL ASSET_GET_LIST (?,?,?,?,?,?,?,?,?,?)";
	String DEVICE_INFO_GET_DEVICE_TYPES_AND_MODELS = "CALL DEVICE_INFO_GET_DEVICE_TYPES_AND_MODELS()";
	String DEVICE_INFO_GET_ALL_DEVICES = "CALL DEVICE_INFO_GET_ALL_DEVICES()";
	String ASSET_TYPE_LIST = "CALL ASSET_TYPE_GET_LIST()";
	String DEVICE_MODEL_LIST = "CALL DEVICE_MODEL_GET_LIST(?)";
	String DEVICE_GET_UNASSIGN_REASON_LIST = "CALL DEVICE_GET_UNASSIGN_REASON_LIST()";

	String DEVICE_INFO_LIST_COUNT = "select FN_GET_DEVICE_INFO_LIST_COUNT(?,?,?,?,?,?) as count";
	String ASSET_LIST_COUNT = "select FN_GET_ASSET_LIST_COUNT(?,?,?,?,?,?) as count";

	String ASSET_DASHBOARD_GET_ASSETS_BY_ASSET_TYPE = "ASSET_DASHBOARD_GET_ASSETS_BY_ASSET_TYPE";
	String ASSET_DASHBOARD_GET_ASSETS_BY_STATUS = "CALL ASSET_DASHBOARD_GET_ASSETS_BY_STATUS(?,?,?)";
	String PET_GET_EXTERNAL_PET_INFO = "CALL PET_GET_EXTERNAL_PET_INFO(?,?)";

	/* firmware version related procedures */
	String FIRMWARE_VERSION_INSERT = "FIRMWARE_VERSION_INSERT";
	String FIRMWARE_VERSION_UPDATE = "FIRMWARE_VERSION_UPDATE";
	String FIRMWARE_VERSION_DELETE = "FIRMWARE_VERSION_DELETE";
	String FIRMWARE_VERSION_GET_BY_ID = "CALL FIRMWARE_VERSION_GET_BY_ID (?)";
	String FIRMWARE_VERSION_GET_LIST = "CALL FIRMWARE_VERSION_GET_LIST (?,?,?,?,?,?,?)";
	String FIRMWARE_VERSION_GET_ALL_VERSIONS = "CALL FIRMWARE_VERSION_GET_ALL_VERSIONS(?,?)";
	String FIRMWARE_VERSION_GET_ALL_VERSIONS_LIST = "CALL FIRMWARE_VERSION_GET_ALL_VERSIONS_LIST()";

	String GET_ASSET_UPDATE_HISTORY = "CALL GET_ASSET_UPDATE_HISTORY(?)";

	String FIRMWARE_VERSION_LIST_COUNT = "select FN_GET_FIRMWARE_VERSION_LIST_COUNT(?,?,?) as count";

	String DEVICE_GET_UNCONGIFURED_DEVICE_LIST = "CALL DEVICE_GET_UNCONGIFURED_DEVICE_LIST()";

	/* users related procedures */
	String USER_INSERT = "USER_INSERT";
	String USER_UPDATE = "USER_UPDATE";
	String USER_UPDATE_PASSWORD = "USER_UPDATE_PASSWORD";
	String USER_DELETE = "USER_DELETE";
	String USER_GET_BY_ID = "USER_GET_BY_ID";
	String USER_GET_LIST = "CALL USER_GET_LIST (?,?,?,?,?,?,?)";
	String LOGIN_GET_USER_DETAILS_BY_USER_NAME = "LOGIN_GET_USER_DETAILS_BY_USER_NAME";
	String USER_GET_PASSWORD_HISTORY_BY_ID = "CALL USER_GET_PASSWORD_HISTORY_BY_ID(?)";
	String USER_PROFILE_UPDATE = "USER_PROFILE_UPDATE";

	String USER_LIST_COUNT = "select FN_GET_USER_LIST_COUNT(?,?,?) as count";

	/* lookup data related procedures */
	String LU_GET_ROLE_TYPES = "call LU_GET_ROLE_TYPES()";
	String LU_GET_MENUS = "call LU_GET_MENUS()";
	String LU_GET_MENU_ACTIONS = "call LU_GET_MENU_ACTIONS()";
	String LU_GET_PET_BREEDS = "call LU_GET_PET_BREEDS()";
	String LU_GET_PET_STATUSES = "call LU_GET_PET_STATUSES()";
	String LU_GET_ROLES = "call LU_GET_ROLES()";
	String LU_GET_ACTIVE_ROLES = "call LU_GET_ACTIVE_ROLES()";
	String LU_GET_MOBILE_APP_CONFIGS = "call LU_GET_MOBILE_APP_CONFIGS()";
	String LU_GET_TICKET_TYPES = "call LU_GET_TICKET_TYPE()";
	String LU_GET_TICKEET_PRIORITIES = "call LU_GET_TICKET_PRIORITY()";
	String LU_GET_TICKET_STATUS = "call LU_GET_TICKET_STATUS()";
	String LU_GET_CUSTOMER_CONTACT_METHODS = "call LU_GET_CUSTOMER_CONTACT_METHOD()";
	String LU_GET_CUSTOMER_CONTACT_REASONS = "call LU_GET_CUSTOMER_CONTACT_REASON()";
	String LU_GET_TICKET_CATEGORIES = "call LU_GET_TICKET_CATEGORY()";
	String LU_GET_ISSUES = "call LU_GET_ISSUES()";
	String LU_GET_ROOT_CAUSE = "call LU_GET_ROOT_CAUSE(?)";
	String LU_GET_AGENT_ACTION = "call LU_GET_AGENT_ACTION(?)";
	String LU_GET_DEFENCIVE_SENSOR_ACTION = "call LU_GET_DEFENCIVE_SENSOR_ACTION()";
	String LU_GET_PET_NAME = "call LU_GET_PET_NAME(?)";
	String LU_GET_PET_PARENT_NAME = "call LU_GET_PET_PARENT_NAME(?)";
	String LU_GET_STUDY_NAME = "call LU_GET_STUDY_NAME(?,?,?)";
	String LU_GET_ACTIVE_STUDY = "call LU_GET_ACTIVE_STUDY(?,?)";
	String LU_GET_SENSOR_NAME = "call LU_GET_SENSOR_NAME(?,?,?)";
	String LU_GET_SENSOR_LOCATION = "call LU_GET_SENSOR_LOCATION()";
	String LU_GET_INVENTORY_STATUS = "call LU_GET_INVENTORY_STATUS(?)";
	String LU_GET_PRIORITY = "call LU_GET_PRIORITY()";
	String LU_GET_USERS = "call LU_GET_USERS()";
	String LU_GET_STATUS = "call LU_GET_STATUS()";
	String LU_GET_CONTACT_METHOD = "call LU_GET_CONTACT_METHOD()";
	String LU_GET_QUESTION_TYPES = "call LU_GET_QUESTION_TYPES()";
	String LU_GET_PRE_DEFINED_INSTRUCTIONS = "call LU_GET_PRE_DEFINED_INSTRUCTIONS()";
	String LU_GET_PRE_DEFINED_QUESTIONS = "LU_GET_PRE_DEFINED_QUESTIONS";
	String LU_GET_POINT_TRACKER_ACTIVITY = "call LU_GET_POINT_TRACKER_ACTIVITY()";
	String LU_GET_DEVICE_LOCATIONS = "call LU_GET_DEVICE_LOCATIONS()";
	String LU_GET_DEVICE_LOCATIONS_BULK_UPLOAD = "call LU_GET_DEVICE_LOCATIONS_BULK_UPLOAD()";
	String LU_GET_DEVICE_STATUSES = "call LU_GET_DEVICE_STATUSES()";
	String LU_GET_MOBILE_APP_FEEDBACK_PAGES = "call LU_GET_MOBILE_APP_FEEDBACK_PAGES()";
	String LU_GET_PET_BEHAVIORS_BY_SPECIES = "call LU_GET_PET_BEHAVIORS_BY_SPECIES(?, ?)";
	String LU_GET_POINT_TRACKER_METRICS = "call LU_GET_POINT_TRACKER_METRICS(?)";
	String LU_GET_POINT_TRACKER_METRICS_BY_ID = "call LU_GET_POINT_TRACKER_METRICS_BY_ID(?)";
	String LU_GET_RACKER_REJECT_REASONS = "call LU_GET_RACKER_REJECT_REASONS()";
	String LU_GET_DEVICE_TYPE = "call LU_GET_DEVICE_TYPE()";
	String LU_GET_DEVICE_MODEL = "call LU_GET_DEVICE_MODEL(?)";
	String LU_GET_ALL_STUDY_NAME = "call LU_GET_ALL_STUDY_NAME()";
	String LU_GET_ACTIVE_STUDY_NAME = "call LU_GET_ACTIVE_STUDY_NAME()";
	String LU_GET_SPECIES = "call LU_GET_SPECIES()";
	String LU_GET_USERS_ASSIGNED_TO_TICKET = "call LU_GET_USERS_ASSIGNED_TO_TICKET()";
	String LU_GET_PET_PARENT_NAME_TIMER = "call LU_GET_PET_PARENT_NAME_TIMER()";
	String LU_GET_PET_NAME_TIMER = "call LU_GET_PET_NAME_TIMER()";
	String LU_GET_CATEGORY_TIMER = "call LU_GET_CATEGORY_TIMER()";
	String LU_GET_PRELUDE_STUDY = "call LU_GET_PRELUDE_STUDY()";
	String LU_GET_EXTRENAL_FILE_CATEGORY = "call LU_GET_EXTRENAL_FILE_CATEGORY()";
	String LU_GET_ALL_CAMPAIGNS = "call LU_GET_ALL_CAMPAIGNS()";
	String LU_GET_QUESTIONNIRE_OCCURANCES = "call LU_GET_QUESTIONNIRE_OCCURANCES()";
	String LU_GET_QUESTIONNIRE_FREQUENCIES = "call LU_GET_QUESTIONNIRE_FREQUENCIES()";
	String LU_GET_MATERIAL_TYPE = "call LU_GET_MATERIAL_TYPE()";
	String LU_GET_MATERIAL_CATEGORY = "call LU_GET_MATERIAL_CATEGORY()";
	String LU_GET_ENTHUSIASM_SCALES = "call LU_GET_ENTHUSIASM_SCALES()";
	String LU_GET_PET_FEEDING_TIMES = "call LU_GET_PET_FEEDING_TIMES()";
	String LU_GET_IMAGE_SCORING_TYPES = "call LU_GET_IMAGE_SCORING_TYPES()";
	String LU_GET_SHIPMENT_COMPANIES = "call LU_GET_SHIPMENT_COMPANIES()";
	String LU_GET_QUESTIONNAIRE_TYPES = "call LU_GET_QUESTIONNAIRE_TYPE()";
	String LU_GET_QUESTIONNAIRE_CATEGORY = "call LU_GET_QUESTIONNAIRE_CATEGORY(?)";

	/* Role related procedures */
	String ROLE_INSERT = "ROLE_INSERT";
	String ROLE_UPDATE = "ROLE_UPDATE";
	String ROLE_DELETE = "ROLE_DELETE";
	String ROLE_GET_BY_ID = "CALL ROLE_GET_BY_ID(?)";
	String ROLE_GET_LIST = "CALL ROLE_GET_LIST (?,?,?,?,?,?,?)";

	String ROLE_LIST_COUNT = "select FN_GET_ROLE_LIST_COUNT(?,?,?) as count";

	/* Mobile App Feedback related procedures & Functions */
	String MOBILE_APP_FEEDBACK_COUNT = "select FN_GET_MOBILE_APP_FEEDBACK_COUNT(?,?,?,?,?) as count";
	String MOBILE_APP_SELF_ONBOARD_COUNT = "select FN_GET_MOBILE_APP_SELF_ONBOARD_COUNT(?,?,?) as count";
	String MOBILE_APP_FEEDBACK_LIST = "call MOBILE_APP_FEEDBACK_LIST (?,?,?,?,?,?,?,?,?,?)";
	String MOBILE_APP_SELF_ONBOARDING_LIST = "call MOBILE_APP_SELF_ONBOARD_GET_LIST (?,?,?,?,?,?,?)";
	String PET_ASSIGN_STUDY = "PET_ASSIGN_STUDY";

	/* AuditLog related Procedures */
	String AUDIT_LOG_INSERT = "audit_log_insert";
	String AUDIT_LOG_GET_LIST = "CALL AUDIT_LOG_GET_LIST(?,?,?,?,?,?,?,?,?,?)";
	String AUDIT_LOG_GET_ACTIVITY = "CALL AUDIT_LOG_GET_ACTIVITY(?,?)";
	String AUDIT_LOG_COUNT = "SELECT FN_GET_AUDIT_LOG_COUNT(?,?,?,?,?,?) as count";

	/* Study related procedures & Functions */
	String STUDY_NOTIFICATION_GET_LIST_COUNT = "select FN_GET_STUDY_NOTIFICATION_LIST_COUNT(?, ?, ?,?) as count";
	String STUDY_NOTIFICATION_GET_LIST = "CALL STUDY_NOTIFICATION_GET_LIST(?, ?, ?, ?, ?, ?, ?,?)";
	String STUDY_NOTIFICATION_UPDATE_STATUS = "STUDY_NOTIFICATION_STATUS_UPDATE";

	String STUDY_GET_LIST_COUNT = "SELECT FN_GET_STUDY_LIST_COUNT(?,?,?,?,?) as count";
	String STUDY_GET_LIST = "CALL STUDY_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String STUDY_GET_ALL_STUDY_LIST = "CALL STUDY_GET_ALL_STUDY_LIST(?)";
	String STUDY_GET_ALL_STUDY_LIST_BY_USER = "CALL STUDY_GET_ALL_STUDY_LIST_BY_USER(?)";
	String STUDY_GET_ALL_STUDY_LIST_ACTIVE_INACTIVE = "CALL STUDY_GET_ALL_STUDY_LIST_ACTIVE_INACTIVE()";
	String STUDY_GET_STUDY_LIST_BY_PET_PARENT_AND_PET = "CALL STUDY_GET_STUDY_LIST_BY_PET_PARENT_AND_PET(?,?)";;
	String STUDY_INSERT = "STUDY_INSERT";
	String STUDY_GET_BY_ID = "STUDY_GET_BY_ID";
	String STUDY_GET_ASSOCIATED_PETS = "CALL STUDY_GET_ASSOCIATED_PETS(?)";
	String STUDY_DISASSOCIATE_PLAN = "STUDY_DISASSOCIATE_PLAN";
	String STUDY_ASSOCIATE_PLAN = "STUDY_ASSOCIATE_PLAN";
	String STUDY_UPDATE = "STUDY_UPDATE";
	String STUDY_DELETE = "STUDY_DELETE";
	String STUDY_DISASSOCIATE_QUESTIONNAIRE = "STUDY_DISASSOCIATE_QUESTIONNAIRE";
	String STUDY_ASSOCIATE_QUESTIONNAIRE = "STUDY_ASSOCIATE_QUESTIONNAIRE";
	String STUDY_UPDATE_QUESTIONNAIRE = "STUDY_UPDATE_QUESTIONNAIRE";
	String STUDY_GET_ASSOCIATED_QUESTIONNAIRES = "CALL STUDY_GET_ASSOCIATED_QUESTIONNAIRES(?)";
	String GET_ALL_PRELUDE_DATA = "CALL GET_ALL_PRELUDE_DATA(?)";
	String GET_PRELUDE_DATA_BY_STUDY = "CALL GET_PRELUDE_DATA_BY_STUDY(?)";
	String GET_ALL_AF_PRELUDE_DATA = "CALL GET_ALL_AF_PRELUDE_DATA(?)";
	String GET_AF_PRELUDE_DATA_BY_STUDY = "CALL GET_AF_PRELUDE_DATA_BY_STUDY(?)";
	

	/* Plan related procedures & Functions */
	String PLAN_GET_LIST_COUNT = "select FN_GET_PLAN_LIST_COUNT(?,?,?,?,?) as count";
	String PLAN_GET_LIST = "CALL PLAN_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String PLANS_INSERT = "PLAN_INSERT";
	String PLAN_DETAILS_VIEW = "CALL PLAN_DETAILS_VIEW(?)";
	String PLAN_GET_PLANS = "CALL PLAN_GET_PLANS(?,?)";
	String PLAN_GET_BY_ID = "PLAN_GET_BY_ID";
	String PLAN_UPDATE = "PLAN_UPDATE";
	String PLAN_DELETE = "PLAN_DELETE";

	/* Pet related procedures & Functions */
	String PET_INSERT = "PET_INSERT";
	String PET_UPDATE = "PET_UPDATE";
	String PET_GET_BY_ID = "PET_GET_BY_ID";
	String PET_GET_BY_ID_AND_STUDY_ID = "CALL PET_GET_BY_ID_AND_STUDY_ID(?,?)";
	String PET_DELETE = "PET_DELETE";
	String PET_GET_ALL_PETS = "CALL PET_GET_ALL_PETS(?)";
	String PET_GET_VIEW_PANE_COUNT = "select FN_GET_PET_VIEW_PANE_COUNT(?,?,?) as count";
	String PET_GET_VIEW_PANE = "CALL PET_GET_VIEW_PANE(?,?,?,?,?)";
	String PET_GET_LIST = "CALL PET_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String FN_GET_PET_OBSERVATIONS_COUNT = "select FN_GET_PET_OBSERVATIONS_COUNT(?,?) as count";
	String PET_GET_OBSERVATIONS_BY_PET_AND_STUDY_ID = "CALL PET_GET_OBSERVATIONS_BY_PET_AND_STUDY_ID(?,?,?,?,?,?)";
	String PET_GET_PARENTS_BY_PET = "CALL PET_GET_PARENTS_BY_PET(?,?,?,?,?)";
	String PET_GET_NOTES_BY_PET = "CALL PET_GET_NOTES_BY_PET(?,?,?,?,?)";
	String PET_GET_DEVICES_BY_PET = "CALL PET_GET_DEVICES_BY_PET(?)";
	String PET_NOTES_INSERT = "PET_NOTES_INSERT";
	String PET_GET_LIST_BY_PET_PARENT = "CALL PET_GET_LIST_BY_PET_PARENT(?)";
	String PET_GET_LIST_COUNT = "select FN_GET_PET_LIST_COUNT(?,?,?,?,?) as count";
	String PET_ASSOCIATE_NEW_STUDY = "PET_ASSOCIATE_NEW_STUDY";
	String PET_ADD_WEIGHT = "PET_ADD_WEIGHT";
	String PET_UPDATE_WEIGHT = "PET_UPDATE_WEIGHT";
	String PET_FEEDING_ENTHUSIASM_SCALE_GET_LIST = "CALL PET_FEEDING_ENTHUSIASM_SCALE_GET_LIST(?,?,?,?,?,?,?,?,?,?)";
	String PET_FEEDING_ENTHUSIASM_SCALE_GET_COUNT = "SELECT FN_GET_PET_FEEDING_ENTHUSIASM_SCALE_COUNT(?,?,?,?,?,?) AS COUNT";
	

	String PET_IMAGE_SCALE_GET_LIST = "CALL PET_IMAGE_SCALE_GET_LIST(?,?,?,?,?,?,?,?,?,?)";
	String PET_IMAGE_SCALE_GET_COUNT = "SELECT FN_GET_PET_IMAGE_SCALE_GET_COUNT(?,?,?,?,?,?) AS COUNT";
	String PET_GET_PARENTS_LIST_COUNT = "SELECT FN_PET_GET_PARENTS_LIST_COUNT(?) AS COUNT";
	String PET_GET_NOTES_LIST_COUNT = "SELECT FN_PET_GET_NOTES_LIST_COUNT(?) AS COUNT";
	String PET_GET_DEVICES_LIST_COUNT = "SELECT FN_PET_GET_DEVICES_LIST_COUNT(?,?) AS COUNT";
	
	String PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET_COUNT = "SELECT FN_PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET_COUNT(?) AS COUNT";
	String PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET = "CALL PET_GET_ACTIVITY_FACTOR_RESULTS_BY_PET(?,?,?,?,?,?)";
	

	String PET_DISASSOCIATE_STUDY = "PET_DISASSOCIATE_STUDY"; // FOR VIEW PET
	String PET_GET_WEIGHT_HISTORY = "CALL PET_GET_WEIGHT_HISTORY_LIST(?,?,?,?,?,?,?,?,?)"; // FOR VIEW PET GRAPH
	String PET_GET_WEIGHT_HISTORY_COUNT = "select FN_GET_PET_WEIGHT_HISTORY_COUNT(?,?,?) as count"; // FOR VIEW PET
																									// GRAPH
	String PET_GET_CURRENT_STUDY_LIST = "CALL PET_GET_CURRENT_STUDY_LIST(?,?)"; // FOR VIEW PET
	String PET_GET_ARCHIVE_STUDY_LIST = "CALL PET_GET_ARCHIVE_STUDY_LIST(?,?)"; // FOR VIEW PET
	String PET_GET_DEVICES_BY_PET_ID_AND_STUDY_ID = "CALL PET_GET_DEVICES_BY_PET_ID_AND_STUDY_ID(?,?,?,?,?,?)"; // FOR
																												// VIEW
																												// PET
	String PET_GET_DETAILS_BY_ID = "PET_GET_DETAILS_BY_ID"; // FOR VIEW PET
	String PET_GET_ALL_CAMPAIGN_POINTS_BY_PET = "call PET_GET_ALL_CAMPAIGN_POINTS_BY_PET(?)"; // FOR VIEW PET CAMPAIGN
																								// POINTS WIDGET
	String PET_GET_CAMPAIGN_POINTS_LIST_COUNT_BY_PET = "SELECT FN_GET_PET_CAMPAIGN_POINTS_LIST_COUNT_BY_PET(?,?) AS COUNT"; // FOR
																															// VIEW
																															// PET
																															// CAMPAIGN
																															// POINTS
																															// LIST
	String PET_GET_CAMPAIGN_POINTS_LIST_BY_PET = "call PET_GET_CAMPAIGN_POINTS_LIST(?,?,?,?,?,?)"; // FOR VIEW PET
																									// CAMPAIGN POINTS
																									// LIST
	String PET_GET_REWARD_POINTS_LIST_COUNT_BY_PET = "SELECT FN_GET_PET_REWARD_POINTS_LIST_COUNT_BY_PET(?) as count"; // FOR
																														// VIEW
																														// PET
																														// CAMPAIGN
																														// POINTS
																														// LIST
	String PET_GET_REDEEMTION_HISTORY_BY_PET = "call PET_GET_REDEEMTION_HISTORY_BY_PET(?)"; // FOR VIEW PET CAMPAIGN
																							// POINTS LIST
	String PET_REDEEM_POINTS = "PET_REDEEM_POINTS"; // FOR VIEW PET
	String PET_GET_EXTERNAL_INFO_LIST = "call PET_GET_EXTERNAL_INFO_LIST(?)"; // FOR ADD/EDIT

	/* Pet Parent related procedures & Functions */
	String PET_PARENT_INSERT = "PET_PARENT_INSERT";
	String PET_PARENT_UPDATE = "PET_PARENT_UPDATE";
	String PET_PARENT_GET_BY_ID = "PET_PARENT_GET_BY_ID";
	String PET_PARENT_GET_ALL = "CALL PET_PARENT_GET_ALL(?)";
	String PET_PARENT_GET_LIST_COUNT = "select FN_GET_PET_PARENT_LIST_COUNT(?,?,?) as count";
	String PET_PARENT_GET_LIST = "CALL PET_PARENT_GET_LIST(?,?,?,?,?,?,?)";
	String PET_PARENT_DELETE = "PET_PARENT_DELETE";

	/* point tracker related procedures */
	String POINT_TRACKER_INSERT = "POINT_TRACKER_INSERT";
	String POINT_TRACKER_GET_LIST_COUNT = "select FN_GET_POINT_TRACKER_LIST_COUNT(?,?,?,?,?,?,?) as count";
	String POINT_TRACKER_GET_LIST = "CALL POINT_TRACKER_LIST(?,?,?,?,?,?,?,?,?,?,?)";
	String POINT_TRACKER_UPDATE = "POINT_TRACKER_UPDATE";
	String POINT_TRACKER_GET_BY_ID = "POINT_TRACKER_GET_BY_ID";
	String POINT_TRACKER_ACTIVITIES_GET_LIST_COUNT = "select FN_GET_POINT_TRACKER_ACTIVITY_LIST_COUNT(?,?,?,?,?,?) as count";
	String POINT_TRACKER_ACTIVITIES_GET_LIST = "CALL POINT_TRACKER_ACTIVITY_LIST(?,?,?,?,?,?,?,?,?,?)";
	String TRACKER_STATUS_UPDATE = "POINT_TRACKER_ACTIVITY_STATUS_UPDATE";
	String FN_GET_POINT_TRACKER_REPORT_COUNT = "select FN_GET_POINT_TRACKER_REPORT_COUNT(?,?,?,?,?,?) as count";
	String GET_POINT_TRACKER_REPORT = "CALL GET_POINT_TRACKER_REPORT(?,?,?,?,?,?,?,?,?,?)";

	/* Support related Procedures & Functions */
	String CUSTOMER_SUPPORT_INSERT = "CUSTOMER_SUPPORT_INSERT";
	String CUSTOMER_SUPPORT_UPDATE = "CUSTOMER_SUPPORT_UPDATE";
	String CUSTOMER_SUPPORT_GET_BY_ID = "CUSTOMER_SUPPORT_GET_BY_ID";
	String CUSTOMER_SUPPORT_DETAILS_GET_BY_ID = "CUSTOMER_SUPPORT_DETAILS_GET_BY_ID";
	String CUSTOMER_SUPPORT_HISTORY_GET_BY_ID = "CUSTOMER_SUPPORT_HISTORY_GET_BY_ID";
	String CUSTOMER_SUPPORT_INSERT_FILE_NAME = "CUSTOMER_SUPPORT_INSERT_FILE_NAME";
	String CUSTOMER_SUPPORT_GET_LIST = "CALL CUSTOMER_SUPPORT_GET_LIST(?,?,?,?,?,?,?,?,?,?,?,?)";
	String CUSTOMER_SUPPORT_GET_LIST_COUNT = "SELECT FN_GET_CUSTOMER_SUPPORT_COUNT(?,?,?,?,?,?,?,?) as count";
	String CUSTOMER_SUPPORT_GET_UPLOADED_FILE = "call CUSTOMER_SUPPORT_GET_UPLOADED_FILE(?,?)";
	String CUSTOMER_SUPPORT_GET_LIST_REPORT_COUNT = "SELECT FN_GET_CUSTOMER_SUPPORT_REPORT_COUNT(?,?,?,?,?,?,?) as count";
	String CUSTOMER_SUPPORT_GET_LIST_REPORT = "CALL CUSTOMER_SUPPORT_GET_LIST_REPORT(?,?,?,?,?,?,?,?,?,?,?)";
	String ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE = "CALL ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE(?,?,?,?,?)";
	String ASSET_DASHBOARD_GET_ASSETS_BY_TICKETS_STUDY = "CALL ASSET_DASHBOARD_GET_ASSETS_BY_TICKETS_STUDY(?,?,?)";
	String FILE_DELETE = "FILE_DELETE";
	String CUSTOMER_SUPPORT_GET_NOW = "SELECT NOW() NOW";

	/* Support Material related procedures & functions */
	String SUPPORT_MATERIAL_INSERT = "SUPPORT_MATERIAL_INSERT";
	String SUPPORT_MATERIAL_GET_LIST_COUNT = "SELECT FN_GET_SUPPORT_MATERIAL_GET_LIST_COUNT(?) as count";
	String SUPPORT_MATERIAL_GET_LIST = "CALL SUPPORT_MATERIAL_GET_LIST(?,?,?,?,?)";
	String SUPPORT_MATERIAL_DETAILS_GET_LIST = "CALL SUPPORT_MATERIAL_DETAILS_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String SUPPORT_MATERIAL_DETAILS_LIST_COUNT = "SELECT FN_GET_SUPPORT_MATERIAL_DETAILS_LIST_COUNT(?,?,?,?,?) as count";
	String SUPPORT_MATERIAL_DETAILS_BY_ID = "SUPPORT_MATERIAL_DETAILS_BY_ID";
	String SUPPORT_MATERIAL_UPDATE = "SUPPORT_MATERIAL_UPDATE";
	String SUPPORT_MATERIAL_VALIDATE_TITLE = "SUPPORT_MATERIAL_VALIDATE_TITLE";
	String SUPPORT_MATERIAL_DELETE = "SUPPORT_MATERIAL_DELETE";

	/* User Favorites related procedures & Functions */
	String USER_FAVOURITE_INSERT = "USER_FAVOURITE_INSERT";
	String USER_FAVOURITE_UPDATE = "USER_FAVOURITE_UPDATE";
	String USER_FAVOURITES_LIST_COUNT = "select FN_GET_USER_FAVOURITES_LIST_COUNT(?,?,?,?,?) as count";
	String USER_FAVOURITE_GET_LIST = "CALL USER_FAVOURITE_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String IS_USER_FAVOURITES = "select FN_GET_IS_USER_FAVOURITES(?,?,?,?) as isFavourite";
	String FN_GET_USER_VALIDATE_ASSOCIATED_STUDY = "select FN_GET_USER_VALIDATE_ASSOCIATED_STUDY(?,?,?) as isStudyExist";

	/* Questionnaires related procedures & Functions */
	String QUESTIONNAIRE_INSERT = "QUESTIONNAIRE_INSERT";
	String QUESTIONNAIRE_UPDATE = "QUESTIONNAIRE_UPDATE";
	String QUESTIONNAIRE_GET_BY_ID = "QUESTIONNAIRE_GET_BY_ID";
	String QUESTIONNAIRE_GET_LIST_COUNT = "SELECT FN_GET_QUESTIONNAIRE_COUNT(?,?,?,?,?) as count";
	String QUESTIONNAIRE_GET_LIST = "CALL QUESTIONNAIRE_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String QUESTIONNAIRE_GET_ALL_LIST = "CALL QUESTIONNAIRE_GET_ALL_LIST()";
	String QUESTIONNAIRE_GET_BY_PET = "CALL QUESTIONNAIRE_GET_BY_PET(?)";
	String QUESTIONNAIRE_DELETE = "QUESTIONNAIRE_DELETE";
	String QUESTIONNAIRE_INSERT_INSTRUCTION = "QUESTIONNAIRE_INSTRUCTION_INSERT";
	String QUESTIONNAIRE_DELETE_INSTRUCTION = "QUESTIONNAIRE_INSTRUCTION_DELETE";
	String QUESTIONNAIRE_UPDATE_INSTRUCTION = "QUESTIONNAIRE_INSTRUCTION_UPDATE";
	String QUESTIONNAIRE_INSERT_QUESTION = "QUESTIONNAIRE_QUESTION_INSERT";
	String QUESTIONNAIRE_DELETE_QUESTION = "QUESTIONNAIRE_QUESTION_DELETE";
	String QUESTIONNAIRE_UPDATE_QUESTION = "QUESTIONNAIRE_QUESTION_UPDATE";
	String QUESTIONNAIRE_GET_ACTIVE_QUESTIONNAIRES = "CALL QUESTIONNAIRE_GET_ACTIVE_QUESTIONNAIRES(?)";
	String QUESTIONNAIRE_RESPONSE_GET_LIST = "CALL QUESTIONNAIRE_RESPONSE_GET_LIST(?,?,?,?,?,?,?,?,?,?)";
	String QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY = "CALL QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY(?,?,?,?,?,?,?,?,?,?,?)";
	String QUESTIONNAIRE_RESPONSE_GET_LIST_COUNT = "SELECT FN_GET_QUESTIONNAIRE_RESPONSE_LIST_COUNT(?,?,?,?,?,?) as count";
	String QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY_COUNT = "SELECT FN_QUESTIONNAIRE_RESPONSE_LIST_BY_STUDY_COUNT(?,?,?,?,?,?,?) as count";
	String QUESTIONNAIRE_RESPONSE_BY_PET_COUNT = "SELECT FN_GET_QUESTIONNAIRE_RESPONSE_BY_PET_COUNT(?,?,?,?,?,?) as count";
	String QUESTIONNAIRE_RESPONSE_LIST_BY_PET = "CALL QUESTIONNAIRE_RESPONSE_LIST_BY_PET(?,?,?,?,?,?,?,?,?,?)";
	String QUESTIONNAIRE_VIEW_RESPONSE_DETAILS = "CALL QUESTIONNAIRE_VIEW_RESPONSE_DETAILS(?,?)";
	String QUESTIONNAIRE_VIEW_RESPONSE = "CALL QUESTIONNAIRE_VIEW_RESPONSE(?)";

	/* Device related procedures & Functions */
	String GET_DEVICE_DETAILS_REPORT = "call GET_DEVICE_DETAILS_REPORT(?,?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_DETAILS_REPORT_COUNT = "select FN_GET_DEVICE_DETAILS_REPORT_COUNT(?,?,?,?,?) as count";

	String GET_DEVICE_MALFUNCTION_REPORT = "call GET_DEVICE_MALFUNCTION_REPORT(?,?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_MALFUNCTION_REPORT_COUNT = "select FN_GET_DEVICE_MALFUNCTION_REPORT_COUNT(?,?,?,?,?) as count";

	String GET_DEVICE_HISTORY_REPORT = "call GET_DEVICE_HISTORY_REPORT(?,?,?,?,?,?,?,?)";
	String FN_GET_DEVICE_HISTORY_REPORT_COUNT = "select FN_GET_DEVICE_HISTORY_REPORT_COUNT(?,?,?,?) as count";

	String FN_GET_DEVICE_INVENTORY_REPORT_COUNT = "select FN_GET_DEVICE_INVENTORY_REPORT_COUNT(?,?,?,?) as count";
	String GET_DEVICE_INVENTORY_REPORT = "call GET_DEVICE_INVENTORY_REPORT(?,?,?,?,?,?,?,?)";

	String FN_GET_DEVICE_TRACKING_REPORT_COUNT = "select FN_GET_DEVICE_TRACKING_REPORT_COUNT(?,?,?,?) as count";
	String GET_DEVICE_TRACKING_REPORT = "call GET_DEVICE_TRACKING_REPORT(?,?,?,?,?,?,?,?)";

	String FN_GET_STUDY_BASED_REPORT_COUNT = "select FN_GET_STUDY_BASED_REPORT_COUNT(?,?,?,?) as count";
	String GET_STUDY_BASED_REPORT = "call GET_STUDY_BASED_REPORT(?,?,?,?,?,?,?,?)";

	String FN_GET_ASSETS_DEVICES_BY_STUDY_REPORT_COUNT = "select FN_GET_ASSETS_DEVICES_BY_STUDY_REPORT_COUNT() as count";
	String ASSET_DASHBOARD_GET_ASSETS_BY_STUDY_STATUS = "ASSET_DASHBOARD_GET_ASSETS_BY_STUDY_STATUS";

	String FN_GET_ASSETS_DEVICES_MALFUNCTIONS_REPORTT = "select FN_GET_ASSETS_DEVICES_MALFUNCTIONS_REPORT() as count";
	String ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE_STUDY = "ASSET_DASHBOARD_GET_ASSETS_BY_ISSUE_TYPE_STUDY";

	/* pets observation media related procedures & Functions */
	String OBSERVATION_MEDIA_GET_LIST = "call OBSERVATION_MEDIA_GET_LIST(?,?,?,?,?,?,?,?,?)";
	String FN_GET_OBSERVATION_MEDIA_COUNT = "select FN_GET_OBSERVATION_MEDIA_COUNT(?,?,?,?,?) as count";
	String OBSERVATION_MEDIA_GET_BY_ID = "call OBSERVATION_MEDIA_GET_BY_ID(?)";

	/* devices info bulk insert. */

	String DEVICE_INFO_BULK_INSERT_STAGING = "INSERT INTO `B_DEVICE_DETAILS_STAGING`(`DEVICE_NUMBER`,`DEVICE_TYPE`,`DEVICE_MODEL`,`DEVICE_LOCATION_NAME`,`MFG_SERIAL_NUMBER`,`MFG_FIRMWARE`,`MFG_MAC_ADDR`,`WIFI_MAC_ADDR`,`USER_ID`,`TRACKING_NUMBER`,`FILE_ATTACHMENT_NAME`,`CREATED_DATE`,`EXCEPTION_TYPE`)VALUES"
			+ "	(?,?,?,?,?,?,?,?,?,?,?,NOW(),?);";
	String DEVICE_INFO_BULK_VALIDATION_STAGING = "DEVICE_INFO_BULK_VALIDATION_STAGING";
	String DEVICE_INFO_BULK_STAGING_RESULTS_DELETE = "DEVICE_INFO_BULK_STAGING_RESULTS_DELETE";
	String DEVICE_INFO_BULK_SAVE = "DEVICE_INFO_BULK_SAVE";
	String DEVICE_INFO_BULK_STAGING_LIST_COUNT = "select FN_GET_DEVICE_INFO_BULK_UPLOAD_LIST_COUNT(?) as count";
	String DEVICE_INFO_BULK_STAGING_LIST = "CALL DEVICE_INFO_BULK_STAGING_LIST (?,?,?)";

	/* Analytical reports */

	String GET_ANALYTICAL_REPORTS_GROUP = "call GET_ANALYTICAL_REPORTS_GROUP()";
	String MANAGE_REPORT_INSERT = "MANAGE_REPORT_INSERT";
	String MANAGE_REPORT_UPDATE = "MANAGE_REPORT_UPDATE";
	String GET_MANAGE_REPORT_GET_BY_ID = "call GET_MANAGE_REPORT_GET_BY_ID(?)";
	String MANAGE_REPORT_DELETE = "MANAGE_REPORT_DELETE";
	String MANAGE_REPORT_LIST_COUNT = "select FN_GET_MANAGE_REPORT_LIST_COUNT(?,?,?) as count";
	String MANAGE_REPORT_GET_LIST = "CALL MANAGE_REPORT_GET_LIST(?,?,?,?,?,?,?)";
	String MANAGE_REPORT_GET_LIST_BY_ID = "CALL MANAGE_REPORT_GET_LIST_BY_ID(?,?)";
	String MANAGE_REPORT_GET_LIST_BY_ID_COUNT = "select FN_GET_MANAGE_REPORT_GET_LIST_BY_ID_COUNT(?,?) as count";

	String PRELUDE_REPORT_GET_LIST_BY_ID = "CALL PRELUDE_REPORT_GET_LIST_BY_ID(?,?,?,?,?,?,?,?)";
	String PRELUDE_REPORT_GET_LIST_BY_ID_COUNT = "select FN_GET_PRELUDE_REPORT_GET_LIST_BY_ID_COUNT(?,?,?,?) as count";

	/* Timer Log */

	String TIMER_LOG_GET_LIST = "CALL TIMER_LOG_GET_LIST(?,?,?,?,?,?,?,?)";
	String TIMER_LOG_GET_LIST_COUNT = " select FN_GET_TIMER_LOG_GET_LIST_COUNT(?,?,?,?) as count";

	/* Image Scoring Scale related procedures */
	String IMAGE_SCORING_SCALE_INSERT = "IMAGE_SCORING_SCALE_INSERT";
	String IMAGE_SCORING_SCALE_UPDATE = "IMAGE_SCORING_SCALE_UPDATE";
	String IMAGE_SCORING_SCALE_DELETE = "IMAGE_SCORING_SCALE_DELETE";
	String IMAGE_SCORING_SCALE_GET_BY_ID = "IMAGE_SCORING_SCALE_GET_BY_ID";
	String IMAGE_SCORING_SCALE_GET_LIST = "CALL IMAGE_SCORING_SCALE_GET_LIST (?,?,?,?,?,?,?,?)";
	String IMAGE_SCORING_SCALE_GET_ACTIVE_LIST = "CALL IMAGE_SCORING_SCALE_GET_ACTIVE_LIST ()";

	String IMAGE_SCORING_SCALE_LIST_COUNT = "select FN_GET_IMAGE_SCORING_SCALE_LIST_COUNT(?,?,?,?) as count";

	/* Study Push Notifications related procedures */
	String PUSH_NOTIFICATOIN_INSERT = "PUSH_NOTIFICATOIN_INSERT";
	String PUSH_NOTIFICATOIN_UPDATE = "PUSH_NOTIFICATOIN_UPDATE";
	String PUSH_NOTIFICATOIN_DELETE = "PUSH_NOTIFICATOIN_DELETE";
	String PUSH_NOTIFICATOIN_GET_BY_ID = "CALL PUSH_NOTIFICATOIN_GET_BY_ID(?)";
	String PUSH_NOTIFICATOIN_GET_LIST = "CALL PUSH_NOTIFICATOIN_GET_LIST (?,?,?,?,?,?,?,?)";

	String PUSH_NOTIFICATOIN_LIST_COUNT = "select FN_GET_PUSH_NOTIFICATOIN_LIST_COUNT(?,?) as count";

	String STUDY_ASSOCIATE_PUSH_NOTIFICATION = "STUDY_ASSOCIATE_PUSH_NOTIFICATION";
	String STUDY_UPDATE_PUSH_NOTIFICATION = "STUDY_UPDATE_PUSH_NOTIFICATION";
	String STUDY_GET_ASSOCIATED_PUSH_NOTIFICATIONS = "CALL STUDY_GET_ASSOCIATED_PUSH_NOTIFICATIONS(?)";
	String STUDY_DISASSOCIATE_PUSH_NOTIFICATION = "STUDY_DISASSOCIATE_PUSH_NOTIFICATION";
	String STUDY_PUSH_NOTIFICATION_GET_ALL_LIST = "CALL STUDY_PUSH_NOTIFICATION_GET_ALL_LIST()";

	String FN_GET_PUSH_NOTIFICATOIN_LIST_COUNT = "select FN_GET_PUSH_NOTIFICATOIN_LIST_COUNT(?,?,?,?) as count";
	
	String SHIPMENT_GET_LIST_COUNT = "select FN_GET_SHIPMENT_GET_LIST_COUNT(?,?) as count";
	String SHIPMENT_GET_LIST = "CALL SHIPMENT_GET_LIST(?,?,?,?,?,?)";
	String SHIPMENT_INSERT = "SHIPMENT_INSERT";
	String SHIPMENT_UPDATE = "SHIPMENT_UPDATE";
	String SHIPMENT_STATUS_UPDATE = "SHIPMENT_STATUS_UPDATE";
	String SHIPMENT_GET_BY_ID = "CALL SHIPMENT_GET_BY_ID(?)";
	String SHIPMENT_DELETE = "SHIPMENT_DELETE";

}
